# Generated by Django 2.2.8 on 2020-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20200826_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='start_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
