# Generated by Django 2.2.8 on 2020-08-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_auto_20200827_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.BroadworksPlatform'),
        ),
    ]
