# Generated by Django 2.2.8 on 2020-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellercount',
            name='reseller_group',
        ),
        migrations.AddField(
            model_name='resellercount',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ResellerGroup',
        ),
    ]
