# Generated by Django 2.2.8 on 2020-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_auto_20201019_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellercount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
