# Generated by Django 2.2.8 on 2020-10-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_auto_20201019_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellercount',
            name='user',
        ),
    ]
