# Generated by Django 2.2.8 on 2020-10-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reseller', '0004_remove_resellercount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=1024)),
                ('client_id', models.CharField(max_length=1024)),
                ('client_secret', models.CharField(max_length=1024)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
