# Generated by Django 2.2.8 on 2020-10-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reseller', '0005_resellerplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellercount',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
