# Generated by Django 2.2.8 on 2020-09-20 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0004_auto_20200814_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcmRouteQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('xmlcfg', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
