# Generated by Django 2.2.8 on 2020-09-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0005_vcmroutequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcmroutequeue',
            name='action',
            field=models.CharField(default='Pending', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vcmroutequeue',
            name='number',
            field=models.CharField(default='+15855551234', max_length=64),
            preserve_default=False,
        ),
    ]
