# Generated by Django 2.2.8 on 2020-09-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0007_vcmroutequeue_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='sansayvcmserver',
            name='client_id',
            field=models.IntegerField(default=1001),
            preserve_default=False,
        ),
    ]
