# Generated by Django 2.2.8 on 2020-10-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0008_sansayvcmserver_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetablelog',
            name='cluster_id',
        ),
        migrations.AddField(
            model_name='routetablelog',
            name='cluster',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sansayvcm_client.SansayCluster'),
            preserve_default=False,
        ),
    ]
