# Generated by Django 2.2.8 on 2020-08-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('platforms', '0003_permissions_platformpermission_platformusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='platformpermission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
