# Generated by Django 2.2.8 on 2020-08-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20200824_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformpermission',
            name='platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platforms.BroadworksPlatform'),
        ),
        migrations.AlterField(
            model_name='platformusers',
            name='platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='platforms.BroadworksPlatform'),
        ),
    ]
