# Generated by Django 2.2.8 on 2020-08-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforms', '0005_auto_20200824_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformusers',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='platformusers',
            name='users',
        ),
        migrations.RemoveField(
            model_name='broadworksplatform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='broadworksplatform',
            name='username',
        ),
        migrations.AddField(
            model_name='broadworksplatform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PlatformPermission',
        ),
        migrations.DeleteModel(
            name='PlatformUsers',
        ),
    ]
