# Generated by Django 2.2.8 on 2020-08-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_auto_20200828_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadworksplatform',
            name='group',
        ),
        migrations.AlterField(
            model_name='broadworksplatform',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
