# Generated by Django 2.2.8 on 2020-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_auto_20200828_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadworksplatform',
            name='password',
            field=models.CharField(default='credentials', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broadworksplatform',
            name='username',
            field=models.CharField(default='username', max_length=1024),
            preserve_default=False,
        ),
    ]
